In [3]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Impact of Ai on Students.zip')

In [2]:
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [6]:
df = df.drop("Student_ID", axis=1)

In [7]:
df

,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  50000 non-null  int64
 1   Major_Category              50000 non-null  object
 2   Year_of_Study               50000 non-null  object
 3   Pre_Semester_GPA            50000 non-null  float64
 4   Weekly_GenAI_Hours          50000 non-null  float64
 5   Primary_Use_Case            50000 non-null  object
 6   Prompt_Engineering_Skill    50000 non-null  object
 7   Tool_Diversity              50000 non-null  int64
 8   Paid_Subscription           50000 non-null  bool
 9   Traditional_Study_Hours     50000 non-null  float64
 10  Perceived_AI_Dependency     50000 non-null  int64
 11  Institutional_Policy        50000 non-null  object
 12  Anxiety_Level_During_Exams  50000 non-null  int64
 13  Post_Semester_GPA           50000 non-null  float64
 14  Skill_Retention_Score       50000 non-null  float64
 15  Burnout_Risk_Level          50000 non-null  object
dtypes: bool(1), float64(5), int64(4), object(6)
memory usage: 5.8+ MB

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include=['object', 'string']):
    df[col] = le.fit_transform(df[col])

In [9]:
df

,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,2,3,2.418,23.31,0,1,1,True,8.13,5,1,6,2.393,86.44,0
1,3,2,3.821,1.12,3,0,5,False,16.65,3,1,9,3.696,69.39,1
2,1,0,3.398,21.26,4,1,2,False,10.35,5,2,9,3.499,73.93,2
3,1,3,3.789,1.82,0,2,4,False,15.23,2,1,2,4.000,63.58,2
4,4,4,3.635,9.29,1,0,4,False,12.55,4,1,4,3.798,100.00,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1,3,2.899,12.16,0,1,2,False,13.36,2,1,2,3.584,66.16,0
49996,4,3,2.870,2.51,0,2,1,False,4.67,3,0,3,3.096,81.62,2
49997,1,3,3.177,15.87,4,0,5,True,3.92,4,1,5,3.605,97.21,0
49998,1,2,3.398,19.91,1,2,5,False,7.10,5,1,3,3.527,84.12,2
49999,0,4,3.242,3.30,0,1,1,False,3.93,2,1,6,3.261,76.16,1